[project]
name = "capstone-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.0.0a9",
    "langchain-openai>=0.3.33",
]
